# Generated by Django 6.0.4 on 2026-05-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_data',
            field=models.TextField(blank=True),
        ),
    ]
